package com.aim.questionnaire.dao;

import com.aim.questionnaire.dao.entity.AutoAnswerEntity;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AutoAnswerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbg.generated
     */
    int insert(AutoAnswerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbg.generated
     */
    int insertSelective(AutoAnswerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbg.generated
     */
    AutoAnswerEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AutoAnswerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AutoAnswerEntity record);

    List<AutoAnswerEntity> selectAll();
}